export const settingsData = [
  {
    title: 'Work time',
    afterClass: 'after-orange',
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing',
    defaultValue: 25,
    step: 5,
    min: 15,
    limit: 40,
    suffix: 'min',
    name: 'work-time',
  },
  {
    title: 'Work iteration',
    afterClass: 'after-dark-turquoise',
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing',
    defaultValue: 5,
    step: 1,
    min: 1,
    limit: 5,
    suffix: '',
    name: 'work-iteration',
  },
  {
    title: 'Short break',
    afterClass: 'after-picton-blue',
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore, voluptates, vero.',
    defaultValue: 1,
    step: 1,
    min: 1,
    limit: 15,
    suffix: 'min',
    name: 'short-break',
  },
  {
    title: 'Long break',
    afterClass: 'after-picton-blue',
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing',
    defaultValue: 45,
    step: 5,
    min: 30,
    limit: 60,
    suffix: 'min',
    name: 'long-break',
  }
];
